import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={`bg-gradient-to-br from-slate-900 via-stone-800 to-sky-700 ${inter.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
